import { Dimensions } from "react-native";

export const BASEURL =
  "https://programminginterviewquestionandanswer.vercel.app/api/v4";

export const SCREEN = {
  WIDTH: Dimensions.get("screen").width,
  HEIGHT: Dimensions.get("screen").height,
};

export const practicequestions = [
  "Find the largest element in an array.",
  "Find the second largest element in an array.",
  "Find the smallest element in an array.",
  "Find the second smallest element in an array.",
  "Reverse an array.",
  "Rotate an array to the left by K positions.",
  "Rotate an array to the right by K positions.",
  "Find the maximum sum subarray (Kadane's Algorithm).",
  "Find the minimum sum subarray.",
  "Find the maximum product subarray.",
  "Find the minimum product subarray.",
  "Find the number of occurrences of a given element in an array.",
  "Find all pairs in an array whose sum is equal to a given number.",
  "Find the missing number in an array of integers from 1 to N.",
  "Find the duplicate element in an array where all elements appear twice except one.",
  "Find the first repeating element in an array.",
  "Find the first non-repeating element in an array.",
  "Find the intersection of two arrays.",
  "Find the union of two arrays.",
  "Move all zeroes to the end of an array.",
  "Find the longest consecutive sequence in an array.",
  "Find the majority element in an array (element that appears more than n/2 times).",
  "Find the k-th largest element in an array.",
  "Find the k-th smallest element in an array.",
  "Find the closest pair to a given sum in an array.",
  "Sort an array of 0s, 1s, and 2s.",
  "Merge two sorted arrays.",
  "Find the maximum difference between two elements such that larger element comes after the smaller one.",
  "Check if an array contains duplicate elements within K distance from each other.",
  "Find if a subarray with zero sum exists.",
  "Find the longest subarray with at most K distinct elements.",
  "Find the longest increasing subsequence in an array.",
  "Find the longest decreasing subsequence in an array.",
  "Find all subsets of an array.",
  "Check if an array is a palindrome.",
  "Find the median of two sorted arrays.",
  "Find the peak element in an array.",
  "Check if a given array can be partitioned into two subsets with equal sum.",
  "Count the number of subarrays with a given sum.",
  "Find the minimum length subarray that sums to a target value.",
  "Find the maximum length of subarray with equal number of 0s and 1s.",
  "Rotate an array by 90 degrees.",
  "Find all triplets in an array that sum up to a given value.",
  "Find the longest repeating subsequence in an array.",
  "Find the longest common prefix among an array of strings.",
  "Check if one array is a rotation of another.",
  "Sort an array of negative and positive numbers.",
  "Rearrange an array in alternating positive and negative numbers.",
  "Count the number of inversions in an array.",
  "Find the smallest subarray with a sum greater than a given value.",
  "Count the frequency of each element in an array.",
  "Find the maximum length subarray with at most two distinct elements.",
  "Find the maximum sum of non-adjacent elements in an array.",
  "Find the longest sequence of consecutive integers in an unsorted array.",
  "Find the smallest element in a rotated sorted array.",
  "Find the number of ways to partition an array into two subsets with equal sum.",
  "Find the longest common subsequence between two arrays.",
  "Find if an array is a subset of another array.",
  "Find the first element that appears only once in an array.",
  "Find the number of unique elements in an array.",
  "Check if an array can form a triangle.",
  "Find the longest substring without repeating characters in an array of characters.",
  "Find the minimum number of platforms required for a railway station.",
  "Find the maximum sum of a subarray with at least one element.",
  "Determine if two arrays are equal.",
  "Find the first index of an element in a sorted array.",
  "Find the intersection of three sorted arrays.",
  "Determine if an array can be divided into two parts such that the sum of both parts is equal.",
  "Check if an array contains a duplicate within a certain distance.",
  "Calculate the product of all elements except the current one.",
  "Determine if an array can be rearranged to form an arithmetic progression.",
  "Find the smallest range that includes at least one element from each of the given arrays.",
  "Find the length of the longest consecutive sequence of integers.",
  "Find the longest substring that contains at most two distinct characters.",
  "Find the maximum product of two integers in an array.",
  "Check if an array can be split into two subsets of equal sum.",
  "Find the longest substring that contains at most K distinct characters.",
  "Count the number of palindromic substrings in an array of characters.",
  "Find the total number of unique paths in a grid.",
  "Calculate the number of distinct ways to climb stairs.",
  "Find the largest rectangular area in a histogram represented by an array.",
  "Find the length of the longest increasing subsequence.",
  "Check if an array contains a cycle.",
  "Find the total number of subsets of a set.",
  "Determine if a given array is sorted.",
  "Count the number of times a given element appears in an array.",
];
